name: Test and Dockerize

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3.1.1
              with:
                  node-version: 16.11.1
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.7.0
              with:
                  mongodb-version: "5.0.7"
            - name: Run tests
              run: npm test
              env:
                  NODE_ENV: development
                  MONGO_URI: mongodb://localhost:27017/express-ts-rest-api
                  MONGO_PASSWORD:
                  API_VERSION: 0.0.1
                  PORT: 8371
    dockerize:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: mirzabicer/express-ts-rest-api:latest
